return {
  {
    "noearc/jieba.nvim",
    dependencies = { "noearc/jieba-lua" },
    lazy = true, -- Don't load on startup
    opts = {
      use_default_mappings = false,
    },
    config = function(_, opts)
      require("jieba_nvim").setup(opts)
    end,
  },

  {
    "chrisgrieser/nvim-spider",
    lazy = true,
    -- keymaps are managed by lang_motion
  },

  {
    "folke/flash.nvim",
    event = "VeryLazy",
    ---@type Flash.Config
    opts = {},
    keys = {
      { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
      { "S", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
      { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
      { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
      { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
    },
  },

  {
    "mluders/comfy-line-numbers.nvim",
    opts = {

      labels = {
        "1",
        "2",
        "3",
        "8",
        "9",
        "11",
        "12",
        "13",
        "18",
        "19",
        "21",
        "22",
        "23",
        "28",
        "29",
        "31",
        "32",
        "33",
        "38",
        "39",
        "41",
        "42",
        "43",
        "48",
        "49",
        "51",
        "52",
        "53",
        "58",
        "59",
        "111",
        "112",
        "113",
        "118",
        "119",
        "121",
        "122",
        "123",
        "128",
        "129",
        "131",
        "132",
        "133",
        "138",
        "139",
        "141",
        "142",
        "143",
        "148",
        "149",
        "151",
        "152",
        "153",
        "158",
        "159",
        "211",
        "212",
        "213",
        "218",
        "219",
        "221",
        "222",
        "223",
        "228",
        "229",
        "231",
        "232",
        "233",
        "238",
        "239",
        "241",
        "242",
        "243",
        "248",
        "249",
        "251",
        "252",
        "253",
        "258",
        "259",
      },
      up_key = "k",
      down_key = "j",

      -- Line numbers will be completely hidden for the following file/buffer types
      hidden_file_types = { "undotree" },
      hidden_buffer_types = { "terminal", "nofile" },
    },
  },
}
